server:
   port: 8084
   contextPath: /
   resetCache: true
spring:
  redis:
    host: 42.192.202.50
    port: 6379
    password: lucifer1qaz@WSX
  http:
    multipart:
      max-file-size: 50M
      max-request-size: 100M
  freemarker:
    suffix: .ftl
# DATASOURCE
jdbc-user:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://42.192.202.50/oauth2-user?autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=Asia/Shanghai
  username: klny
  password: lucifer1qaz@WSX
jdbc:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://42.192.202.50/vote?autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=Asia/Shanghai
  username: klny
  password: lucifer1qaz@WSX

#jdbc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: root
#    password:
#jdbc-hfc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/hfc?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: root
#    password:


# MyBatis

mybatis:
    typeAliasesPackage: com.lucifer
    mapperLocations: classpath:/sqlmaps/*.xml
    configLocation: classpath:/mybatis-config.xml

qiniu:
  accessKey: 0eQGsXVlK2ZMC0zrY-WwG0RAGN2XGhR-MuZ43obW
  secretKey: E4Oi-dh-0xg3ehU8BBJkS63Aon8HVXs4fd7BRNxk
  publicBucket: klny-vote-p
  url: http://qn-vote-p.klny.xyz/
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 30Mb
solr:
  url:
    news: http://test.haifuc.cn:8983/solr/news
    artist: http://test.haifuc.cn:8983/solr/artist
    appreciate: http://test.haifuc.cn:8983/solr/appreciate
sms:
  sendCodeUrl: https://api.netease.im/sms/sendcode.action
  appKey: 80f0cbe03428deb5f520005694aeffdd
  appSecret: ef2c21102cb8
  verifyCodeUrl: https://api.netease.im/sms/verifycode.action
wx:
  appId: wx1b792045969d2147
  secret: 34a9d9d86dc36f30320c89763780b23e
  loginAppId: wx1b792045969d2147
  loginSecret: 34a9d9d86dc36f30320c89763780b23e
vote:
  start: '2022-07-03 00:00:00'
  deadline: '2022-07-17 00:00:00'
wxLoginRedirect:
  devlopment: http://localhost:8080/category
  production: https://vote.klny.xyz/category






